//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoPaperWorkProcessSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public global::MetroFramework.MetroThemeStyle Theme {
            get {
                return ((global::MetroFramework.MetroThemeStyle)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::MetroFramework.MetroColorStyle Style {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["Style"]));
            }
            set {
                this["Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color GridHeaderColor {
            get {
                return ((global::System.Drawing.Color)(this["GridHeaderColor"]));
            }
            set {
                this["GridHeaderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color GridHeaderFontColor {
            get {
                return ((global::System.Drawing.Color)(this["GridHeaderFontColor"]));
            }
            set {
                this["GridHeaderFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_38.asmx/getCustomerList?COMPANY_NAME=@COMPANY_NAME&COMP" +
            "ANY_NAME_READING=@COMPANY_READING&BILL_COMPANY_NAME=@BILL_COMPANY_NAME&COMPANY_N" +
            "O_BOX=@COMPANY_NO_BOX&ACCOUNT_NAME=@ACCOUNT_NAME")]
        public string CustomerList {
            get {
                return ((string)(this["CustomerList"]));
            }
            set {
                this["CustomerList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_38.asmx/UpdateCustomer")]
        public string CustomerUpdate {
            get {
                return ((string)(this["CustomerUpdate"]));
            }
            set {
                this["CustomerUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_31.asmx/ConfirmationOfTransfer?strFromDate=@FromDate&st" +
            "rToDate=@ToDate")]
        public string GetBankTR {
            get {
                return ((string)(this["GetBankTR"]));
            }
            set {
                this["GetBankTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_33.asmx/ConfirmationOfTransfer_NonAmigo?strDTMID=@DTMID" +
            "")]
        public string NonAmigo_BankTR {
            get {
                return ((string)(this["NonAmigo_BankTR"]));
            }
            set {
                this["NonAmigo_BankTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_32.asmx/ConfirmationOfTransfer_Amigo?strDTMID=@DTMID")]
        public string Amigo_BankTR {
            get {
                return ((string)(this["Amigo_BankTR"]));
            }
            set {
                this["Amigo_BankTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_32.asmx/ConvertAmigoToNonAmigo")]
        public string AmigoToNonAmigo {
            get {
                return ((string)(this["AmigoToNonAmigo"]));
            }
            set {
                this["AmigoToNonAmigo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_33.asmx/ConvertNonAmigoToAmigo")]
        public string NonAmigoToAmigo {
            get {
                return ((string)(this["NonAmigoToAmigo"]));
            }
            set {
                this["NonAmigoToAmigo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_34.asmx/ConfirmOfComparisonResult?strFromDate=@FromDate" +
            "&strToDate=@ToDate")]
        public string ConfirmOfComparisonResult {
            get {
                return ((string)(this["ConfirmOfComparisonResult"]));
            }
            set {
                this["ConfirmOfComparisonResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_36.asmx/GetUnmatchInvoice?strFromDate=@FromDate&strToDa" +
            "te=@ToDate")]
        public string GetUnmatchInvoice {
            get {
                return ((string)(this["GetUnmatchInvoice"]));
            }
            set {
                this["GetUnmatchInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_35.asmx/CancelAllocation")]
        public string CancelAllocation {
            get {
                return ((string)(this["CancelAllocation"]));
            }
            set {
                this["CancelAllocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_36.asmx/RefundProcess?SEQID=@SEQID")]
        public string RefundProcess {
            get {
                return ((string)(this["RefundProcess"]));
            }
            set {
                this["RefundProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://localhost:6077/opt_37.asmx/GetDataFor37?TRANSACTION_TYPE=@TRANSACTION_TYPE&FROM_YEAR_MONTH=@FROM_YEAR_MONTH&TO_YEAR_MONTH=@TO_YEAR_MONTH&FROM_STATUS_PLAN_DEPOSIT_YYMM=@FROM_STATUS_PLAN_DEPOSIT_YYMM&TO_STATUS_PLAN_DEPOSIT_YYMM=@TO_STATUS_PLAN_DEPOSIT_YYMM&FROM_STATUS_ACTUAL_DEPOSIT_DATE=@FROM_STATUS_ACTUAL_DEPOSIT_DATE&TO_STATUS_ACTUAL_DEPOSIT_DATE=@TO_STATUS_ACTUAL_DEPOSIT_DATE&DEPOSIT_RULE=@DEPOSIT_RULE&WITH_OR_WITHOUT_PAYMENT=@WITH_OR_WITHOUT_PAYMENT&BILL_SUPPLIER_NAME=@BILL_SUPPLIER_NAME")]
        public string GetDataForGrid37 {
            get {
                return ((string)(this["GetDataForGrid37"]));
            }
            set {
                this["GetDataForGrid37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_37.asmx/UpdateInvoice")]
        public string UpdateInvoice {
            get {
                return ((string)(this["UpdateInvoice"]));
            }
            set {
                this["UpdateInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_35.asmx/GetAccountingCSV?strFromDate=@FromDate&strToDat" +
            "e=@ToDate")]
        public string Get35_AccountingCSV {
            get {
                return ((string)(this["Get35_AccountingCSV"]));
            }
            set {
                this["Get35_AccountingCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://localhost:6077/opt_37.asmx/Scheduled_Payment?TRANSACTION_TYPE=@TRANSACTION_TYPE&FROM_YEAR_MONTH=@FROM_YEAR_MONTH&TO_YEAR_MONTH=@TO_YEAR_MONTH&FROM_STATUS_PLAN_DEPOSIT_YYMM=@FROM_STATUS_PLAN_DEPOSIT_YYMM&TO_STATUS_PLAN_DEPOSIT_YYMM=@TO_STATUS_PLAN_DEPOSIT_YYMM&FROM_STATUS_ACTUAL_DEPOSIT_DATE=@FROM_STATUS_ACTUAL_DEPOSIT_DATE&TO_STATUS_ACTUAL_DEPOSIT_DATE=@TO_STATUS_ACTUAL_DEPOSIT_DATE&DEPOSIT_RULE=@DEPOSIT_RULE&WITH_OR_WITHOUT_PAYMENT=@WITH_OR_WITHOUT_PAYMENT&BILL_SUPPLIER_NAME=@BILL_SUPPLIER_NAME")]
        public string Schedule_Payment {
            get {
                return ((string)(this["Schedule_Payment"]));
            }
            set {
                this["Schedule_Payment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://localhost:6077/opt_37.asmx/Account_Receivable?TRANSACTION_TYPE=@TRANSACTION_TYPE&FROM_YEAR_MONTH=@FROM_YEAR_MONTH&TO_YEAR_MONTH=@TO_YEAR_MONTH&FROM_STATUS_PLAN_DEPOSIT_YYMM=@FROM_STATUS_PLAN_DEPOSIT_YYMM&TO_STATUS_PLAN_DEPOSIT_YYMM=@TO_STATUS_PLAN_DEPOSIT_YYMM&FROM_STATUS_ACTUAL_DEPOSIT_DATE=@FROM_STATUS_ACTUAL_DEPOSIT_DATE&TO_STATUS_ACTUAL_DEPOSIT_DATE=@TO_STATUS_ACTUAL_DEPOSIT_DATE&DEPOSIT_RULE=@DEPOSIT_RULE&WITH_OR_WITHOUT_PAYMENT=@WITH_OR_WITHOUT_PAYMENT&BILL_SUPPLIER_NAME=@BILL_SUPPLIER_NAME")]
        public string Account_Receivable {
            get {
                return ((string)(this["Account_Receivable"]));
            }
            set {
                this["Account_Receivable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1300, 640")]
        public global::System.Drawing.Size DefaultDimentions {
            get {
                return ((global::System.Drawing.Size)(this["DefaultDimentions"]));
            }
            set {
                this["DefaultDimentions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_37.asmx/AllocationManualCompletion?ALLOCATE=@ALLOCATE&S" +
            "EQ_NO=@SEQ_NO&COMPANY_NO_BOX=@COMPANY_NO_BOX&YEAR_MONTH=@YEAR_MONTH&RECEIPT_ALLO" +
            "CATION_DATE=@RECEIPT_ALLOCATION_DATE&INVOICE_ALLOCATION_DATE=@INVOICE_ALLOCATION" +
            "_DATE")]
        public string ManualAllocationComplete {
            get {
                return ((string)(this["ManualAllocationComplete"]));
            }
            set {
                this["ManualAllocationComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_35.asmx/GetMatchInvoice?strFromDate=@FromDate&strToDate" +
            "=@ToDate&strNoReserved=@NoReserved")]
        public string GetMatchInvoice {
            get {
                return ((string)(this["GetMatchInvoice"]));
            }
            set {
                this["GetMatchInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_3B.asmx/do_ManualAllocation?COMPANY_NO_BOX=@COMPANY_NO_" +
            "BOX&YEAR_MONTH=@YEAR_MONTH")]
        public string ManualAllocation {
            get {
                return ((string)(this["ManualAllocation"]));
            }
            set {
                this["ManualAllocation"] = value;
            }
        }
    }
}
